// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXeJhlCFUwSi-zUPF8PBTm2EpwohEBiTA',
    appId: '1:662710155134:web:71e72221bc23e138a9252f',
    messagingSenderId: '662710155134',
    projectId: 'apppromotor-37c5d',
    authDomain: 'apppromotor-37c5d.firebaseapp.com',
    storageBucket: 'apppromotor-37c5d.firebasestorage.app',
    measurementId: 'G-GQR1BZZDWY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhSY2X9SCwv0L9qAbuPirGDqN5nhcGibU',
    appId: '1:662710155134:android:a069ae51e5db7acda9252f',
    messagingSenderId: '662710155134',
    projectId: 'apppromotor-37c5d',
    storageBucket: 'apppromotor-37c5d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4U9fili0otobEWbbMH2PQxVgsDFu0QeY',
    appId: '1:662710155134:ios:5cb8f54785a2623ca9252f',
    messagingSenderId: '662710155134',
    projectId: 'apppromotor-37c5d',
    storageBucket: 'apppromotor-37c5d.firebasestorage.app',
    iosBundleId: 'com.example.flutterfireconfigure',
  );
}
